### ISSUE TITLE
Error when connecting to LDAP

### ISSUE THREAD

**Issue by basketas** [lkarlslund/adalanche#1]
Hi, the tool just gives error when connecting to LDAP.. 

![image](https://user-images.githubusercontent.com/16399561/126414873-63822940-ed26-4755-b604-a8607bce55a2.png)

As you can see, DC is discovered correctly..

**Comment by lkarlslund** [comment]
Could be a certificate issue. If you have no CA infrastructure or the client doesn't trust the AD cert this is the result. 

If you use -tlsmode NoTLS you also need -port 389

**Comment by basketas** [comment]
This was it.. Thanks :)
