### ISSUE TITLE
Thrown error when trying to build (commit ec6691c2b31837fd6130d3445b5f643e2542060d)

### ISSUE THREAD

**Issue by jaredbarez** [lkarlslund/adalanche#12]
`go build -ldflags "-X github.com/lkarlslund/adalanche/modules/version.Program=adalanche -X github.com/lkarlslund/adalanche/modules/version.Builddate=20220401 -X github.com/lkarlslund/adalanche/modules/version.Commit=ec6691c -X github.com/lkarlslund/adalanche/modules/version.Version=v2022.2.1-34-gec6691c-local-changes" -o adalanche-windows-x64-v2022.2.1-34-gec6691c-local-changes.exe ./adalanche`

`# github.com/lkarlslund/adalanche/modules/integrations/activedirectory/analyze
modules\integrations\activedirectory\analyze\analyze-ad.go:1195:32: undefined: strings.Cut
modules\integrations\activedirectory\analyze\analyze-ad.go:1225:32: undefined: strings.Cut`

**Comment by lkarlslund** [comment]
Please use Golang 1.18 to compile adalanche

**Comment by jaredbarez** [comment]
OK, thanks (it compiles now). readme.md is still on 1.17 tough.
