### ISSUE TITLE
FR: Deselect/Select all button on analysis methods/Analysis objects

### ISSUE THREAD

**Issue by ch0wm3in** [lkarlslund/Adalanche#13]
Hi,

Great work with the tool really nice!
I think it would make sense to add a Deselect All and Select all button under those blades where theres potentially a lot of clicking to be done, eg Analysis methods. See example below
![image](https://user-images.githubusercontent.com/32718507/169119864-0c7f01b2-781f-480a-a64a-3713eba57a6b.png)

For example if you only want to see Generic all, i have to click a lot, whereas if a deselect all button was there it would be four clicks.

**Comment by lkarlslund** [comment]
Thanks for the suggestion, this is in the upcoming commercial version.
