### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bill-e-ghote** [lkarlslund/adalanche#15]
Executables built on my Linux VM from a fresh git clone taken just now. I even went so far as to remove my ~/go dir and allow that to be rebuilt as part of the build.sh process. Please advise.

![image](https://user-images.githubusercontent.com/2491041/173066448-6318f718-63fd-4ad2-a533-dad5641947ae.png)

**Comment by lkarlslund** [comment]
Yes, that was a bug :) Try it now.

**Comment by bill-e-ghote** [comment]
At least it's not panicking, but not quite working as expected. This same error output occurs whether I take the default options or specify "collect activedirectory". Also, I'm not sure how to specify the domain - every time I tried the app claimed "No domain specified, auto-detecting". It got the domain right, so that's not an issue anyway.

![image](https://user-images.githubusercontent.com/2491041/173151698-ba8c15cf-3a8e-46df-8e7c-72e387e093d3.png)

**Comment by lkarlslund** [comment]
This should be fixed now.

**Comment by lkarlslund** [comment]
Closing as resolved
