### ISSUE TITLE
ERR problem collecting Active Directory objects: failed to get values for object NNNNN: no results for attribute type 4

### ISSUE THREAD

**Issue by bill-e-ghote** [lkarlslund/Adalanche#17]
I saved a snapshot of one of my domains on 6/9 and again today. Adalanche fails to collect from either snapshot, with the same error (object number varies between the two snaps) for both snapshots. This is using win-x64 binary built from a git pull performed on June 15.

![image](https://user-images.githubusercontent.com/2491041/174408195-e7bd7f51-e7b0-40cd-94a5-27380d004285.png)

**Comment by bill-e-ghote** [comment]
I tried again with a fresh build taken from source pull just now, with the same result.

**Comment by lkarlslund** [comment]
OK, I think you have an attribute containing a blank string. I've changed the code to allow for this, I hope this fixes your issue.

**Comment by bill-e-ghote** [comment]
Thanks for the try, but it seems not to have fixed my issue. I pulled the update and rebuilt, but the error persists. Is there a way for me to get more info? The --debug flag did not emit anything different than without it.

**Comment by lkarlslund** [comment]
I don't really know what's wrong, if you're getting the same output?

If you can share a dump with the problem privately, I can fix it. Feel free to reach out via Twitter if you're interested.

**Comment by bill-e-ghote** [comment]
Thanks for the offer to fix if I were to share the dump. However, even privately is not an option for me due to work policy. Perhaps I can try to instrument the code to find the underlying issue, but I've had no time to work on it in these past two weeks. Possibly I can revisit this later...
