### ISSUE TITLE
Collection on DC without username/password

### ISSUE THREAD

**Issue by asekhar** [lkarlslund/Adalanche#18]
It will be great to have an option equivalent to "SharpHound.exe --CollectionMethods All,GPOLocalGroup" that allows collecting data from a domain controller as local system rather than having to specify a username/password.

**Comment by lkarlslund** [comment]
I'm not sure what you're asking, adalanche can already do this?

If you run "adalanche collect activedirectory" directly on a DC, it should work just as if you were doing it remote.

You can force localhost by using --server=127.0.0.1

If you want to force local GPO paths, use --gpopath="C:\Windows\SYSVOL\sysvol\domain.local\Policies" but the logic in adalanche would disable ACL analysis for GPO files then (that's the way it's done at the moment)

**Comment by asekhar** [comment]
When i run it as system with the options specified, i get the following error:

```LDAP Result Code 200 "Network Error": write tcp 10.128.0.8:56458->10.128.0.8:636: wsasend: An existing connection was forcibly closed by the remote host.```

**Comment by lkarlslund** [comment]
Try --port=389 --tlsmode=NoTLS, you probably don't have working CA infrastructure?

**Comment by asekhar** [comment]
that worked. thanks.

**Comment by ll3N1GmAll** [comment]
I too am getting the same error. Using adalanche.exe --port=398 --tlsmode=NoTLS throws errors about --port and --tlsmode being "unknown flags". --help provides no insight about these proposed options.

**Comment by ll3N1GmAll** [comment]
using this worked:
 adalanche.exe collect activedirectory --port=398 --tlsmode=NoTLS
