### ISSUE TITLE
Adalanche Collect not working - panic: Exception occurred. (<nil>)

### ISSUE THREAD

**Issue by R41z0r** [lkarlslund/Adalanche#20]
.\adalanche.exe collect localmachine
{"level":"warn","time":"2022-08-04T12:45:59+02:00","message":"Problem loading preferences: open preferences.json: The system cannot find the file specified."}
12:45:59.22 INF adalanche  v2022.5.19 (commit 02ddc47) built 20220519, (c) 2020-2022 Lars Karlslund, This program comes with ABSOLUTELY NO WARRANTY
panic: Exception occurred. (<nil>)

goroutine 1 [running]:
github.com/go-ole/go-ole/oleutil.MustGetProperty(0xc0000a4678?, {0xaeade4?, 0xc0001049e0?}, {0x0?, 0xc000104dc0?, 0xc000104d00?})
        /home/runner/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/oleutil/oleutil.go:72 +0x5e
github.com/amidaware/taskmaster.parseRegisteredTask(_)
        /home/runner/go/pkg/mod/github.com/amidaware/taskmaster@v0.0.0-20220111015025-c9cd178bbbf2/parse.go:67 +0x279
github.com/amidaware/taskmaster.(*TaskService).GetRegisteredTasks.func1(0x9?)
        /home/runner/go/pkg/mod/github.com/amidaware/taskmaster@v0.0.0-20220111015025-c9cd178bbbf2/manage.go:174 +0x7b
github.com/go-ole/go-ole/oleutil.ForEach(0x1?, 0xc00013b6d8)
        /home/runner/go/pkg/mod/github.com/go-ole/go-ole@v1.2.6/oleutil/oleutil.go:122 +0x20d
github.com/amidaware/taskmaster.(*TaskService).GetRegisteredTasks(0xc00013c750)
        /home/runner/go/pkg/mod/github.com/amidaware/taskmaster@v0.0.0-20220111015025-c9cd178bbbf2/manage.go:171 +0x2d0
github.com/lkarlslund/adalanche/modules/integrations/localmachine/collect.Collect({0xade5ae, 0x4})
        /home/runner/work/adalanche/adalanche/modules/integrations/localmachine/collect/main.go:283 +0xf3f
github.com/lkarlslund/adalanche/modules/integrations/localmachine/collect.Execute(0x160ba00?, {0xade6b2?, 0x0?, 0x0?})
        /home/runner/work/adalanche/adalanche/modules/integrations/localmachine/collect/main.go:50 +0x6e
github.com/spf13/cobra.(*Command).execute(0x160ba00, {0x16922c0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x160b000)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/lkarlslund/adalanche/modules/cli.Run()
        /home/runner/work/adalanche/adalanche/modules/cli/main.go:117 +0x60d
main.main()
        /home/runner/work/adalanche/adalanche/adalanche/main.go:15 +0x19

**Comment by lkarlslund** [comment]
Hi,

1) What OS are you running this under?
2) Are you running this elevated or not?
3) Error happens in an external module, so probably not an Adalanche thing, but let's see if we can narrow it down.

Thanks,

Lars

**Comment by lkarlslund** [comment]
Closing due to no response.
