### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by MickeyDB** [lkarlslund/Adalanche#27]
**OS**: Windows
**Elevated**: yes
**Command**: .\adalanche-windows-amd64-v2023.5.3.exe
`12:13:07.999  WARNING  Scheduled task: \\REDACTED\SYSVOL\REDACTED\scripts\Modify-CIMV2\Set-cimV2.bat ... FIXME!
12:13:08.040  INFORMA  Loaded 83 files, skipped 0 files
12:13:08.643  INFORMA  Loader Active Directory produced 9929 objects in 1 collections
12:13:08.664  INFORMA  Loader Group Policy produced 1301 objects in 1 collections
12:13:08.665  INFORMA  Loader LocalMachine JSON file produced 1 objects in 1 collections
12:13:08.666  INFORMA  We produced a total of 11231 objects from data
12:13:08.919  INFORMA  Domain REDACTED has a incoming trust with REDACTED
Preprocessing Active Directory priority BeforeMergeHigh [11332/22664] ██████████████████████████████████████████████████████████████████████████████                                                                              50.00% | 0spanic: runtime error: index out of range [65535] with length 511

goroutine 218 [running]:
github.com/lkarlslund/adalanche/modules/engine.(*Object).get(0xc002887d80?, 0x7da0?)
        /home/runner/work/Adalanche/Adalanche/modules/engine/object.go:486 +0x76
github.com/lkarlslund/adalanche/modules/engine.(*Object).attr(0xffff00c00085ad30?, 0x39e0?)
        /home/runner/work/Adalanche/Adalanche/modules/engine/object.go:500 +0x25
github.com/lkarlslund/adalanche/modules/engine.(*Object).Attr(0x12232d4?, 0x508?)
        /home/runner/work/Adalanche/Adalanche/modules/engine/object.go:512 +0x34
github.com/lkarlslund/adalanche/modules/integrations/activedirectory/analyze.init.0.func32.1(0xc0008fa9c0)
        /home/runner/work/Adalanche/Adalanche/modules/integrations/activedirectory/analyze/analyze-ad.go:689 +0x54
github.com/lkarlslund/adalanche/modules/engine.(*Objects).Iterate.func1(0x2887e98?, 0xc00104be48?)
        /home/runner/work/Adalanche/Adalanche/modules/engine/objects.go:460 +0x22
github.com/SaveTheRbtz/generic-sync-map-go.(*MapOf[...]).Range(0xc001b58088?, 0xc002887f20?)
        /home/runner/go/pkg/mod/github.com/!save!the!rbtz/generic-sync-map-go@v0.0.0-20230201052002-6c5833b989be/map.go:334 +0x2ba
github.com/lkarlslund/adalanche/modules/engine.(*Objects).Iterate(0xc001882998?, 0xc004791268?)
        /home/runner/work/Adalanche/Adalanche/modules/engine/objects.go:459 +0x45
github.com/lkarlslund/adalanche/modules/integrations/activedirectory/analyze.init.0.func32(0xc0006d4920?)
        /home/runner/work/Adalanche/Adalanche/modules/integrations/activedirectory/analyze/analyze-ad.go:685 +0x35
github.com/lkarlslund/adalanche/modules/engine.Process.func1({0x1700ab0, {0x124587a, 0x32}, 0x3, 0x0})
        /home/runner/work/Adalanche/Adalanche/modules/engine/edgeanalyzers.go:70 +0x5a
created by github.com/lkarlslund/adalanche/modules/engine.Process
        /home/runner/work/Adalanche/Adalanche/modules/engine/edgeanalyzers.go:69 +0x277`

**Comment by lkarlslund** [comment]
Good catch! This is because Adalanche weren't able to find any certificateTemplate attributes in your AD ... so at least you don't have that to worry about. Should be fixed in the latest pre-release build

**Comment by MickeyDB** [comment]
Used devleopment build and worked like a charm, thanks!
