### ISSUE TITLE
Collector not working

### ISSUE THREAD

**Issue by LasseKrache** [lkarlslund/Adalanche#28]
I tried Adalanche today on a test system: adalanche-windows-amd64-v2023.5.3.exe runs without problems, but the collector version generates this message:

```
C:\Temp>adalanche-collector-windows-386-v2023.5.3.exe
14:33:58.303  INFORMA  Adalanche Open Source v2023.5.3 (commit aa4c038), (c) 2020-2022 Lars Karlslund, This program comes with ABSOLUTELY NO WARRANTY
Error: Problem accessing output folder: mkdir : The system cannot find the path specified.
Usage:
   [flags]

Flags:
  -h, --help                  help for this command
      --logfile string        Log file
      --logfilelevel string   Log file log level (default "info")
      --loglevel string       Console log level (default "info")
      --outputpath string     Dump output JSON file in this folder

14:33:58.315   ERROR   Error: Problem accessing output folder: mkdir : The system cannot find the path specified.
14:33:58.316   ERROR   Failed to execute
```
Have I missed something? I also get the same error running the program as an administrator ...

Best regards and thank you very much for this amazing tool!
Lasse

**Comment by lkarlslund** [comment]
You need --outputpath [existing-path-to-place-your.json] for it to work ...

**Comment by LasseKrache** [comment]
OMG! :-O
This is so ... (missing words!)

Sorry, and thank you very much! I really appreciate your work!

Have a nice weekend,
Lasse
