### ISSUE TITLE
no required module provides package 1Th-.exe; to add it:

### ISSUE THREAD

**Issue by dcdiagfix** [lkarlslund/adalanche#4]
when trying to build on Windows 10 20h2 get the below error

fatal: not a git repository (or any of the parent directories): .git
no required module provides package 1Th-.exe; to add it:
        go get 1Th-.exe
package 1Th- is not in GOROOT (C:\Program Files\Go\src\1Th-)
package 1Th- is not in GOROOT (C:\Program Files\Go\src\1Th-)
no required module provides package 1Th-.exe; to add it:
        go get 1Th-.exe

**Comment by lkarlslund** [comment]
Can you provide information on what you're doing? Providing only some error output is not enough information. 

If you want to build it on Windows, I'd recommend using the build.cmd file which is included.

Also there are pre-built binaries availble.

**Comment by lkarlslund** [comment]
![image](https://user-images.githubusercontent.com/8929787/137307274-06778fbe-8857-432b-8e7d-18c22785c78f.png)

I hope you have more success running it than compiling it! :-)
