### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by logcode-dot-com** [lkarlslund/Adalanche#41]
Hello, in the https://github.com/lkarlslund/Adalanche#easy-mode--full-auto you say
> All your data files (are belong to us), and will end up in the data subfolder (or use --datapath dir to use an alternative folder).

What do you mean by "are belong to us"?

Regards,
 Örjan

**Comment by lkarlslund** [comment]
It's a meme.
 https://en.m.wikipedia.org/wiki/All_your_base_are_belong_to_us
