### ISSUE TITLE
Unable to open transferred output file

### ISSUE THREAD

**Issue by AhmedAA** [lkarlslund/adalanche#6]
After running the collector on a target, and getting the output back on a Kali host, adalanche seems to struggle with actually analysing the file.

According to the documentation, the output files must be placed in a folder called `data`. This folder will be created automatically when invoking adalanche, if it does not exist.
The folder however, is being created without execution permissions on a linux host, which means that it is broken. Files cannot be copied into the folder etc.

Furthermore, after making the folder executable (and moving an outputfile in), adalanche skips reading the file.

Testing information:
- HOST: kali linux
- ADALANCHE VERSION: Latest release (downloaded pre-compiled binaries)

See screenshots for further details:
No data folder existing
![image](https://user-images.githubusercontent.com/1724181/143569537-8fb57d9c-e408-457d-ab7d-f862a0b8dbfb.png)

Data folder created automatically, but with wrong permissions
![image](https://user-images.githubusercontent.com/1724181/143569688-92dea1f4-718d-4bf9-8e53-5c8634bbbc95.png)

JSON file not picked up by adalanche, even though it is in the correct folder
![image](https://user-images.githubusercontent.com/1724181/143569808-edb194ee-aebf-4051-be14-f8e68208fd5e.png)

I would personally prefer being able to point to where data should be loaded from, on starting `adalanche analyze`.

**Comment by lkarlslund** [comment]
adalanche identifies data files by their suffix.

For collector data it expects .localmachine.json for it to load it, and default the collector should output files with that suffix.

For all commands you can use --datapath /your/data/folder to override the default "data".

I've committed a fix for the data folder creation attributes. Thanks for the bug report!

**Comment by AhmedAA** [comment]
The collector did create a file with a very long and tedious name yes :D 
When transferring files, it is cumbersome, so I just renamed the file to something easier to handle for me.

I will retest with renaming the file and repoert back!

**Comment by AhmedAA** [comment]
Renaming the file to a suffix with `localmachine.json` makes adalanche pick it up.

Thanks!

I think it would be a good idea to have it in the readme or documentation that the suffix is a requirement. Otherwise this can be closed I guess :)

**Comment by lkarlslund** [comment]
Glad you've got it working.

I've added this to the readme as suggested.
