### ISSUE TITLE
How to combine collected data from multiple domains/forests ?

### ISSUE THREAD

**Issue by jaredbarez** [lkarlslund/adalanche#7]
Could you please explain how to combine the data from multiple domains/forests? Can I drop all in the single data directory ? Something else ?
Also what is the meaning of FML triplet in UI ? What excatly happens when I switch these ? Is there any more detailed docs or blogpost besides README.md ?

Thanks

**Comment by lkarlslund** [comment]
It's up to you how to structure the datapath folder. For multi forest analysis I put each forest in its own subfolder, but you can also put everything in the same folder, but it's a complete mess when you then want to update the data for a single forest later. But adalanche just loads the stuff you point it to, and uses filename extensions to figure out what is what.

FML triplet is First, Middle, Last. So if you don't want a pwn(edge) or object type you can disable it. For instance the search "What can Authenticated Users do?" usually ends with lots of groups they are a member of, but maybe that doesn't make sense - then you can uncheck "group" object type from L and get rid of those results.

For multi forest analysis you should use latest pre-release as of now. Hope this helps!

**Comment by jaredbarez** [comment]
Thanks for response!
