### ISSUE TITLE
Feature request: back "button" option

### ISSUE THREAD

**Issue by jaredbarez** [lkarlslund/adalanche#8]
It would be nice to have an option to quickly go back to the previous graph(s) after finishing drilling down paths. Thanks

**Comment by lkarlslund** [comment]
This can be added if it's possible to store cytoscape.js state (nodes, edges, layout, zoom level) in a serialized form and restore it back again.

**Comment by jaredbarez** [comment]
It is just a suggestion (not in position to place a "request" :-) so if you find worth it please add it to TODO list. Thanks
