### ISSUE TITLE
Warning error parsing data - on mS-DS-ConsistencyGuid

### ISSUE THREAD

**Issue by burgervan** [lkarlslund/adalanche#9]
First run of Adalanche and this error when parsing the data.

09:33:04.22 INF Will process 225 files
Loading data  98% |███████████████████████████████████████ | (13822/14052, 22010 tidbits/s) [1s:0s]09:33:05.22 WRN Failed to convert attribute mS-DS-ConsistencyGuid value <<SNIP>> to GUID: uuid: UUID must be exactly 16 bytes long, got 36 bytes
panic: tried to set attribute mS-DS-ConsistencyGuid to NO values

goroutine 37 [running]:
github.com/lkarlslund/adalanche/modules/engine.(*Object).SetValues(0xc003e80063, 0x97d0, {0xc002ef64f0, 0x674851, 0xc0030715a0})
        /home/runner/work/adalanche/adalanche/modules/engine/object.go:508 +0xdd
github.com/lkarlslund/adalanche/modules/integrations/activedirectory.(*RawObject).ToObject(0xc00b6fd800, 0x1)
        /home/runner/work/adalanche/adalanche/modules/integrations/activedirectory/rawobject.go:42 +0x1e5
github.com/lkarlslund/adalanche/modules/integrations/activedirectory/analyze.(*ADLoader).Init.func1()
        /home/runner/work/adalanche/adalanche/modules/integrations/activedirectory/analyze/adloader.go:67 +0x70
created by github.com/lkarlslund/adalanche/modules/integrations/activedirectory/analyze.(*ADLoader).Init
        /home/runner/work/adalanche/adalanche/modules/integrations/activedirectory/analyze/adloader.go:64 +0xc9

**Comment by lkarlslund** [comment]
Thanks for the bug report. 

It looks like that attribute is not binary encoded but just the ASCII representation of UUID. I've added robustness for this to the code, you can try with the freshly built [development build](https://github.com/lkarlslund/adalanche/releases/tag/latest)

Let me know if that works for you.

**Comment by burgervan** [comment]
Fixed! Thanks.
